### ISSUE TITLE
Installation fails if the database is set to SQLite

### ISSUE THREAD

**Issue by Spomky** [mykiwi/symfony-bootstrapped#19]
When creating a `.env.local` file with the following database url: ``, I have the following error: `DATABASE_URL=sqlite:///%kernel.project_dir%/var/data.db`

```sh
gosu foo php -r echo "Wait database...\n"; set_time_limit(30); require __DIR__."/config/bootstrap.php"; $u = parse_url($_ENV["DATABASE_URL"]); for(;;) { if(@fsockopen($u["host"].":".($u["port"] ?? 3306))) { break; }}
Wait database...
make: *** [Makefile:53: db] Error 255
```

**Comment by mykiwi** [comment]
You should drop, or update this line to ignore the check when `DATABASE_URL` starts with `sqlite:///`
https://github.com/mykiwi/symfony-bootstrapped/blob/master/Makefile#L53

**Comment by Spomky** [comment]
OK understood.
Many thanks.
